port: 4000
host: localhost
safe: false

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, vendor]
include: ['surveys/', 'surveys/2015/', 'faq/', 'blog/']
permalink: /:title ## disables post output
timezone: null
lsi: false

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


#pygments is not supported by GitHub. See https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors
#See also https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
#We have to use rouge
# Hint by http://milanaryal.com/2015/writing-on-github-pages-and-jekyll-using-markdown/ and http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
#markdown: redcarpet
#redcarpet:
#  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

### required for main site and faq/
## blog posts are stored in _posts (as usual), but served at blog/
collections:
- faq
- sections

### content configuration ###
title:       "JabRef"
keywords:    "JabRef, bibtex, biblatex, bibliography, editor"
description: "Graphical Java application for managing bibtex (.bib) databases"
source_link: "https://github.com/JabRef/www.jabref.org/"
favicon:     favicon.ico #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: UA-74055103-1 ## put YOUR key here to enable tracking! (blank to disable)

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  lightgray: '#e0e0e0'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  jabref-font:     '#4d4674'
  light-turquoise: '#d0f7fb'
